# Generated by Django 2.1.7 on 2019-02-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Name of the bucket used in your Models.', max_length=250)),
                ('description', models.CharField(blank=True, help_text='Human readable description of what this bucket is.', max_length=250, null=True)),
                ('version', models.IntegerField(default=0)),
            ],
        ),
    ]
