# Generated by Django 2.1.7 on 2019-02-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumpet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databucket',
            name='name',
            field=models.SlugField(help_text='Name of the bucket used in your Models.', max_length=250, unique=True),
        ),
    ]
